### ISSUE TITLE
Please write js logic for movement of the chess pieces.

### ISSUE THREAD

**Issue by akash-vartak** [StoneCypher/chessboard_html#2]
Please write js logic for movement of the chess pieces.

**Comment by StoneCypher** [comment]
oh hi :smile: 

man i haven't looked at this in ages

lemme see about that, sure

**Comment by StoneCypher** [comment]
looks like there already is

https://github.com/StoneCypher/chessboard_html/blob/master/chessboard.html#L12

**Comment by akash-vartak** [comment]
the js shown is not logic for movement, but, you can ask for help by creating an issue in your own repo...making it available to all by - adding a license and by putting it out on various forums like quora, stackoverflow, etc.

**Comment by StoneCypher** [comment]
er, it's not about asking for help

lines 13-15 pull the piece id and new location from three elements in the html

change those to arguments instead and you're done

**Comment by StoneCypher** [comment]
it's because it's so easy to do that i thought you just didn't notice it

please consider how it might seem to people that you come onto their repositories, ask them for things, and when they say "it's already in there," you tell them to go to stackoverflow and ask for help

maybe you should?

**Comment by akash-vartak** [comment]
ummm, my bad,  i didn't realise the potential of the javascript...and i suggested you stackoverflow cause i thought of helping you to advance in the project...
Anyways, thanks all the same.

By the way the JS isn't working properly, it has a weird bug. can put my finger on it though.

**Comment by akash-vartak** [comment]
<h4>Plus i think you should label this thread as enhancement.</h4>

**Comment by StoneCypher** [comment]
the reason i wrote this repo was to show a friend how to use css transitions to accomplish animation, as the readme states.

the repo also already has a license.  it's mit.

i feel that this repo has achieved the goal i had for it.  you are welcome to fork it and continue the process, if you like.
